require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - config/**/*
    - spec/**
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.2.2

Layout/LineLength:
  Max: 140

Layout/CommentIndentation:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/StringLiterals:
  Enabled: false

Style/QuotedSymbols:
  EnforcedStyle: same_as_string_literals

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
