version: '3.8'

services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: reservation_db
    restart: always
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web_network

  web:
    container_name: reservation_web
    build: .
    env_file:
      - .env.rails
    environment:
      RAILS_ENV: "development"
      RAILS_MAX_THREADS: "5"
      PORT: "3000"
    volumes:
      - .:/web
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  pgdata:
